accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'),
         name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

my_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mysite/', include('mysite.urls')),
    path('', include('pages.urls')),
    path('accounts/', include('accounts.urls')),
]

mysite/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index),
    path('<int:content_id>/', views.detail, name='detail'),
    path('comment/create/<int:content_id>/', views.comment_create, name='comment_create'),
    path('comment/update/<int:comment_id>/', views.comment_update, name='comment_update'),
    path('comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
]

pages/urls.py
from django.urls import path

from . import views

urlpatterns = [
 path('', views.mainpage),
 path('company/', views.company),
]

accounts/models.py
from django.db import models

# Create your models here.

mysite/models.py
from django.db import models
from django.contrib.auth.models import User


class MainContent(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.title


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content_list = models.ForeignKey(MainContent, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)
    modify_date = models.DateTimeField(auto_now=True)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

mysite/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

accounts/views.py
from django.contrib.auth import login
from django.shortcuts import render, redirect
from accounts.forms import SignupForm


def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/')
    else:
        form = SignupForm()
    return render(request, 'accounts/signup.html', {'form': form})

mysite/views.py
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from .models import MainContent, Comment
from .forms import CommentForm


@login_required(login_url='accounts:login')
def comment_update(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)

    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.save()
            return redirect('detail', content_id=comment.content_list.id)
    else:
        form = CommentForm(instance=comment)

    context = {'comment': comment, 'form': form}
    return render(request, 'mysite/comment_form.html', context)


@login_required(login_url='accounts:login')
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)

    if request.user != comment.author:
        raise PermissionDenied
    else:
        comment.delete()
    return redirect('detail', content_id=comment.content_list.id)


def index(request):
    content_list = MainContent.objects.order_by('-pub_date')
    context = {'content_list': content_list}
    return render(request, 'mysite/content_list.html', context)


def detail(request, content_id):
    content_list = get_object_or_404(MainContent, pk=content_id)
    context = {'content_list': content_list}
    return render(request, 'mysite/content_detail.html', context)


@login_required(login_url='accounts:login')
def comment_create(request, content_id):
    content_list = get_object_or_404(MainContent, pk=content_id)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.content_list = content_list
            comment.author = request.user
            comment.save()
            return redirect('detail', content_id=content_list.id)
    else:
        form = CommentForm()
        context = {'content_list': content_list, 'form': form}
        return render(request, 'mysite/content_detail.html', context)

pages/views.py
from django.shortcuts import render


def mainpage(request):
    return render(request, 'pages/mainpage.html')


def company(request):
    return render(request, 'pages/company_info.html')

templates/accounts/login.html
{% extends "base.html" %}
{% block content %}
{% if form.errors %}
<p>아이디 또는 비밀번호가 틀립니다. 다시 시도해주세요.</p>
{% endif %}
<form method="post" action="{% url 'accounts:login' %}">
    {% csrf_token %}
    <table>
        <tr>
            <td>{{ form.username.label_tag }}</td>
            <td>{{ form.username }}</td>
        </tr>
        <tr>
            <td>{{ form.password.label_tag }}</td>
            <td>{{ form.password }}</td>
        </tr>
    </table>
    <input type="submit" value="login">
</form>
<a href="{% url 'accounts:signup' %}">signup</a>
{% endblock %}

templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<h2>Sign up</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign Up</button>
</form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Mysite</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
</head>
<body>
{% include "navbar.html" %}
{% block content %}
{% endblock %}
{% include "footer.html" %}
</body>
</html>

templates/footer.html
<!-- Footer-->
<footer class="py-5 bg-dark">
 <div class="container px-4 px-lg-5"><p class="m-0 text-center text-white">Copyright &copy;
Your Website 2021</p></div>
</footer>

templates/mysite/comment_form.html
{% extends 'base.html' %}
{% block content %}
<h2> update comment</h2>
<section class="mb-5">
    <div class="card bg-light">
        <div class="card-body">
            <form method="post" class="mb-4" action="{% url 'comment_update' comment.id %}">
                {% csrf_token %}
                <textarea id="content" name="content" class="form-control"
                          rows="3">{{ form.content.value }}</textarea>
                <button type="submit" class="btn btn-primary">submit</button>
            </form>
        </div>
    </div>
</section>
{% endblock %}

templates/mysite/content_detail.html
{% extends 'base.html' %}
{% block content %}
<h2>{{ content_list.title }}</h2>
<div>
    {{ content_list.content }}
</div>
<section class="mb-5">
    <div class="card bg-light">
        <div class="card-body">
            <form method="post" class="mb-4" action="{% url 'comment_create' content_list.id %}">
                {% csrf_token %}
                <textarea id="content" name="content" class="form-control" rows="3"
                          placeholder="내용을 입력해주세요."></textarea>
                <button type="submit" class="btn btn-primary">submit</button>
            </form>
            {% for comment in content_list.comment_set.all %}
            <div class="d-flex">
                <div class="ms-3">
                    <div class="fw-bold">{{ comment.author.username }} &nbsp&nbsp
                        {{ comment.create_date }}
                        {% if comment.create_date != comment.modify_date %}
                        / 수정일자: {{ comment.modify_date }}
                        {% endif %}
                        {% if request.user == comment.author %}
                        <a href="{% url 'comment_update' comment.id%}" class="btn btn-sm btn-outlinesecondary">수정</a>
                        <a href="{% url 'comment_delete' comment.id%}" class="btn btn-sm btn-outlinesecondary">삭제</a>
                        {% endif %}
                    </div>
                    {{ comment.content }}
                </div>
            </div>
            <br/>
            {% endfor %}
        </div>
    </div>
</section>

{% endblock %}

templates/mysite/content_list.html
{% extends 'base.html' %}
{% block content %}

<!-- Page Content-->
<div class="container px-4 px-lg-5">
    <!-- Heading Row-->
    {% if content_list %}
    {% for content in content_list %}
    <div class="row gx-4 gx-lg-5 align-items-center my-5">
        <div class="col-lg-7"><img class="img-fluid rounded mb-4 mb-lg-0"
                                   src="https://dummyimage.com/900x400/dee2e6/6c757d.jpg" alt="..."/>
        </div>
        <div class="col-lg-5">
            <h1 class="font-weight-light">{{ content.title }}</h1>
            <p>{{ content.content | truncatewords:30}}</p>
            <a class="btn btn-primary" href="{% url 'detail' content.id %}">상품 상세보기</a>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <p>content 가 없습니다.</p>
    {% endif %}
    <!-- Call to Action-->
    <div class="card text-white bg-secondary my-5 py-4 text-center">
        <div class="card-body"><p class="text-white m-0">This call to action card is a great place to showcase some
            important information or display a clever tagline!</p></div>
    </div>
    <!-- Content Row-->
    <div class="row gx-4 gx-lg-5">
        <div class="col-md-4 mb-5">
            <div class="card h-100">
                <div class="card-body">
                    <h2 class="card-title">Card One</h2>
                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem magni quas ex
                        numquam, maxime minus quam molestias corporis quod, ea minima accusamus.</p>
                </div>
                <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">More Info</a></div>
            </div>
        </div>
        <div class="col-md-4 mb-5">
            <div class="card h-100">
                <div class="card-body">
                    <h2 class="card-title">Card Two</h2>
                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod tenetur ex natus
                        at dolorem enim! Nesciunt pariatur voluptatem sunt quam eaque, vel, non in id dolore voluptates
                        quos eligendi labore.</p>
                </div>
                <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">More Info</a></div>
            </div>
        </div>
        <div class="col-md-4 mb-5">
            <div class="card h-100">
                <div class="card-body">
                    <h2 class="card-title">Card Three</h2>
                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem magni quas ex
                        numquam, maxime minus quam molestias corporis quod, ea minima accusamus.</p>
                </div>
                <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">More Info</a></div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/navbar.html
<!-- Responsive navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="/">django company</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bstarget="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" ariaexpanded="false"
                aria-label="Toggle navigation"><span class="navbar-togglericon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link" href="/company/">company
                    info</a></li>
                <li class="nav-item"><a class="nav-link" href="/mysite/">product</a></li>
                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">{{ user.username }} (logout)</a></li>
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">login</a></li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>

templates/pages/company_info.html
{% extends 'base.html' %}
{% block content %}
<h1>회사소개 페이지입니다.</h1>
{% endblock %}

templates/pages/mainpage.html
{% extends 'base.html' %}
{% block content %}
<h1>메인 페이지입니다.</h1>
{% endblock %}

templates/pages/navbar.html
<ul class="navbar-nav mb-2 mb-lg-0">
    <li class="nav-item"><a class="nav-link" href="/company/">company info</a></li>
    <li class="nav-item"><a class="nav-link" href="/mysite/">product</a></li>
    {% if user.is_authenticated %}
    <li class="nav-item"><a class="nav-link" href="{% url
'accounts:logout' %}">{{ user.username }} (logout)</a></li>
    {% else %}
    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">login</a></li>
    {% endif %}
</ul>